### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by bwente** [tasianmedia/cookieJar#7]
Can you change the log from ERROR to DEBUG?

My MODX error log is filling up with "getCookie() - Cookie name not recognised." My boss thinks it is an error, but it isn't. Most visitors won't have the cookie I am looking for on that page. It is only for special visitors to another page that get that cookie.

**Comment by davidpede** [comment]
Makes sense. see pr https://github.com/tasianmedia/cookieJar/pull/8

Will release package update shortly
